// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PigeonFancierTracker.Infrastructure.Persistence;

#nullable disable

namespace PigeonFancierTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720094805_AddSyncRunItems")]
    partial class AddSyncRunItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.RawApiSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedFancierId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint", "NormalizedQuery", "SelectedFancierId", "SourceSeasonId", "BodySha256");

                    b.ToTable("RawApiSnapshots");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.SyncRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedFancierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.SyncRunItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RawSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SyncRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncRunId", "Endpoint", "NormalizedQuery");

                    b.ToTable("SyncRunItems");
                });
#pragma warning restore 612, 618
        }
    }
}
