// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PigeonFancierTracker.Infrastructure.Persistence;

#nullable disable

namespace PigeonFancierTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820105751_AddWeatherToFlight")]
    partial class AddWeatherToFlight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.CompletedTransferEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<int>("BidCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PigeonName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedFancierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seller")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SoldPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldTo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StartPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("TransferEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("TransferStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelectedFancierId", "TransferId")
                        .IsUnique();

                    b.ToTable("CompletedTransfers");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.FlightEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Department")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistanceCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocationLng")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResultsFetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Subscribers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WeatherBeaufort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("WeatherCapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherCondition")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("WeatherDay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WeatherHumidity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeatherTemperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeatherWind")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Season", "Status");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.FlightResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageSpeed")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FancierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PigeonDistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PigeonName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalParticipants")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FancierId");

                    b.HasIndex("FlightId", "PigeonId")
                        .IsUnique();

                    b.ToTable("FlightResults");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.FoodDistributionSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Barley")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int>("Corn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Peanut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedFancierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelectedFancierId", "CapturedAtUtc");

                    b.ToTable("FoodDistributionSnapshots");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.OffspringCacheEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OffspringJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PigeonId")
                        .IsUnique();

                    b.ToTable("OffspringCache");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.PedigreeCacheEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PedigreeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PigeonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PigeonId")
                        .IsUnique();

                    b.ToTable("PedigreeCache");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.RawApiSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedFancierId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint", "NormalizedQuery", "SelectedFancierId", "SourceSeasonId", "BodySha256");

                    b.ToTable("RawApiSnapshots");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.SponsorSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanCallSponsors")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ContractEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Direct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monthly")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuntimeRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedFancierId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Signed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SponsorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelectedFancierId", "CapturedAtUtc");

                    b.ToTable("SponsorSnapshots");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.SyncRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedFancierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("PigeonFancierTracker.Infrastructure.Persistence.SyncRunItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RawSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SyncRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncRunId", "Endpoint", "NormalizedQuery");

                    b.ToTable("SyncRunItems");
                });
#pragma warning restore 612, 618
        }
    }
}
